name = "panel-tahsin"
compatibility_date = "2025-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "panel-tahsin-db"
database_id = "4538586f-4436-46c3-a6b0-97d45f21b21e"
